### ISSUE TITLE
TileObjectGroup.objects return the same group not the objects

### ISSUE THREAD

**Issue by hikaruAi** [atomicptr/openfl-tiled#58]
TileObjectGroup.objects return a  Array of objects, but the objects.x,y, height, width are the always the ObjectGroup.x, y, height, width.

**Comment by atomicptr** [comment]
confirmed

**Comment by atomicptr** [comment]
If you need TiledObjects please use the development version of openfl-tiled for now. I'll push the next version (which contains the fix) probably at the end of the week.

```
haxelib git openfl-tiled git@github.com:kasoki/openfl-tiled.git dev
```

**Comment by hikaruAi** [comment]
Thanks :)
