### ISSUE TITLE
Error at TiledObjectGroup.hx

### ISSUE THREAD

**Issue by smoketh** [atomicptr/openfl-tiled#63]
line 84: objects.push(xml); should be objects.push(child); or else you just parse same xml of TiledObjectGroup

**Comment by atomicptr** [comment]
https://github.com/kasoki/openfl-tiled/blob/dev/openfl/tiled/TiledObjectGroup.hx#L84 ? Looks like object.push(child) for me

**Comment by smoketh** [comment]
Awkward. I did the pull from the haxelib, what was the last time since you pushed updates?

**Comment by atomicptr** [comment]
Yes, you need to use the dev branch (try "haxelib git **repo**")
